CREATE DATABASE COMPANYDB;
USE COMPANYDB;

CREATE TABLE Employee1(
SSN CHAR(9) PRIMARY KEY,
BD DATE,
GENDER VARCHAR(10),
FNAME VARCHAR(25) NOT NULL,
LNAME VARCHAR(25) NOT NULL ,
Superid CHAR(9),
CONSTRAINT FK_EMP_Supervisor FOREIGN KEY (Superid)REFERENCES Employee1(SSN)
 );

CREATE TABLE Dept (
DNUM INT PRIMARY kEY ,
DNAME VARCHAR(35) NOT NULL ,
HIRE_DATE DATE ,
SSN_EMP CHAR(9)
CONSTRAINT FK_EMP_MANAGER FOREIGN KEY (SSN_EMP)REFERENCES Employee1(SSN)
);


CREATE TABLE Locations (
DNUM INT NOT NULL  ,
LOCATION VARCHAR(100) NOT NULL,
PRIMARY KEY (DNUM ,LOCATION)
);

CREATE TABLE Project (
PNUM INT PRIMARY KEY,
PNAME VARCHAR(100) NOT NULL , 
CITY VARCHAR(100),
LOCATION VARCHAR(100),
Dnum INT NOT NULL,
CONSTRAINT FK_Project_Dept FOREIGN KEY (Dnum) REFERENCES Dept(Dnum)
);

CREATE TABLE EMP_PRO(
HOURS VARCHAR(20),
PNUM INT,
SSN_ID CHAR(9),
PRIMARY KEY (SSN_ID, PNUM),
FOREIGN KEY (SSN_ID) REFERENCES Employee1(SSN),
FOREIGN KEY (PNUM) REFERENCES Project(PNUM)
);

 
CREATE TABLE Dependent (
SSN CHAR(9),
DEPENDENT_NAME VARCHAR(100),
GENDER CHAR(10),
BD DATE,
PRIMARY KEY (SSN, DEPENDENT_NAME),
FOREIGN KEY (SSN) REFERENCES Employee1(SSN)
);